site_name: University of Arizona General Surgery Practice Management Guidelines
site_url: https://surgery-residency.com
repo_url: https://github.com/bilalmirza96/VanderbiltGeneralSurgery
edit_uri: edit/main/docs/
copyright: |
  Copyright © 2025 University of Arizona General Surgery
docs_dir: 'docs'

plugins:
  - search
  - awesome-pages
  - autolinks
  - glightbox
  # - mdx_spanner
  - git-revision-date-localized:
      enable_creation_date: true
  - print-site:
      add_to_navigation: true
      print_page_title: 'Print Site'
      add_print_site_banner: true
      enumerate_headings: false
      enumerate_figures: false

theme:
  name: material
  custom_dir: overrides
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  favicon: images/ua-favicon.png            # <— supply this file
  logo: images/ua-logo-white.png            # <— white-on-dark UA logo
  features:
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: arizona-general-surgery        # optional: your org/user
      repo: vimbook                        # optional: your repo shortlink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bilalmirza96/VanderbiltGeneralSurgery
  feedback:
    title: Was this page helpful?
    ratings:
      - icon: material/emoticon-happy-outline
        name: This page was helpful
        data: 1
        note: >-
          Thank you! Help us improve this page by
          using our <a href="https://github.com/bilalmirza96/VanderbiltGeneralSurgery/issues/new/?title=[Feedback]+{title}+-+{url}" target=_blank>feedback form</a>.
      - icon: material/emoticon-sad-outline
        name: This page could be improved
        data: 0
        note: >-
          Thanks for your feedback! Help us improve this page by
          using our <a href="h
