site_name: University of Arizona General Surgery Handbook
site_url: https://surgery-residency.com
repo_url: https://github.com/bilalmirza96/VanderbiltGeneralSurgery
edit_uri: edit/main/docs/
copyright: |
  Copyright © 2025 University of Arizona General Surgery
docs_dir: 'docs'
plugins:
  - search
  - awesome-pages
  - autolinks
  - glightbox
  # - mdx_spanner
  - git-revision-date-localized:
      enable_creation_date: true
  - print-site:
      add_to_navigation: true
      print_page_title: 'Print Site'
      add_print_site_banner: true
      enumerate_headings: false
      enumerate_figures: false
theme:
  name: material
  custom_dir: overrides
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  logo: logo/UA_logo.png
  favicon: logo/ua-favicon.png
  features:
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
